package com.droid.dorpee.utils.preference

interface PreferenceAttribute {
    companion object {
        const val PREFERENCE_NAME = "FON_HOME_PREFERENCE"
        const val IS_USER_LOGIN = "isUserLogin"
        const val USER = "user"
        const val CARD = "card"
        const val USER_TYPE = "userType"
        const val USER_NAME = "userName"
        const val FIRST_NAME = "firstName"
        const val LAST_NAME = "lastName"
        const val ADDRESS = "address"
        const val IS_ADDRESS = "isAddress"
        const val MOBILE_NUMBER = "mobileNumber"
        const val EMAIL_ADDRESS = "emailAddress"
        const val SERVICES = "services"
        const val TYPES = "types"
        const val INTERESTS = "interests"
        const val VENUE_TYPES = "venuetypes"
        const val VENUE_RES = "venueresponse"
        const val ALL_VENUE_RES = "allVenueResponse"
        const val BLOCK_OUT_RES = "blockInOutResponse"
        const val ENVIRONMENT = "Environment"
        const val ASSETS = "Assets"
        const val PLANID = "plan_id"
        const val PLANCREDITS = "plan_credits"
        const val REMAINCREDITS = "remain_credits"
        const val EXPIRYPLAN = "plan_expiry"
        const val PLANNAME = "plan_name"
        const val ISActivePlan = "active_plan"
        const val CARDBRAND = "card_brand"
        const val LASTFOUR = "last_four"
        const val ISCARDACTIVE = "active_card"
        const val WORKSPACE = "workspace"
        const val OPENINGDATE = "openingDate"
        const val SELECTDATE = "selectedDate"
        const val CLOSINGDATE = "closingDate"
        const val NUMBERPEOPLE = "numberPeople"
        const val EMPCOMPANY = "emp_company"
        const val EMPCREDITS = "emp_credits"
        const val EMPID = "emp_id"
        const val IsEmployee = "isCompanyEmployee"
        const val VenueName = "venueName"
        const val TokenId = "tokenID"

    }
}